# Generated by Django 5.1.15 on 2026-09-09 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150, verbose_name='Restaurant Name')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('legal_entity_name', models.CharField(blank=True, max_length=200, verbose_name='Legal Entity Name')),
                ('gstin', models.CharField(help_text='15-digit Indian GST Identification Number', max_length=15, verbose_name='GSTIN')),
                ('fssai_number', models.CharField(help_text='14-digit FSSAI License Number', max_length=14, verbose_name='FSSAI License No.')),
                ('email', models.EmailField(max_length=254, verbose_name='Contact Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('website', models.URLField(blank=True, null=True)),
                ('address_line1', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(default='Hyderabad', max_length=100, verbose_name='City')),
                ('state', models.CharField(default='Telangana', max_length=100, verbose_name='State')),
                ('pincode', models.CharField(default='500034', max_length=10, verbose_name='PIN Code')),
                ('country', models.CharField(default='India', max_length=50, verbose_name='Country')),
                ('currency', models.CharField(default='INR', max_length=10, verbose_name='Currency')),
                ('currency_symbol', models.CharField(default='₹', max_length=5, verbose_name='Currency Symbol')),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50, verbose_name='Timezone')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurant_logos/')),
                ('opening_time', models.TimeField(default='10:00')),
                ('closing_time', models.TimeField(default='23:30')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
            },
        ),
        migrations.CreateModel(
            name='RestaurantSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_cgst_percent', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('default_sgst_percent', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('default_service_charge_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_tax_inclusive', models.BooleanField(default=False, verbose_name='Tax-Inclusive Pricing')),
                ('invoice_prefix', models.CharField(default='INV', max_length=10)),
                ('bill_footer_message', models.TextField(default='Thank you for dining with us! FSSAI Lic: Certified.')),
                ('enable_table_reservations', models.BooleanField(default=True)),
                ('enable_kds', models.BooleanField(default=True)),
                ('enable_delivery_dispatch', models.BooleanField(default=True)),
                ('low_stock_alert_threshold', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
