# Generated by Django 5.1.15 on 2026-09-09 05:43

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Coupon Code')),
                ('title', models.CharField(max_length=150, verbose_name='Offer Title')),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage (%) Off'), ('FLAT', 'Flat (₹) Amount Off')], default='PERCENTAGE', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount Value (% or ₹)')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Min Order Value (₹)')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Max Cap (₹)')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Valid From')),
                ('valid_to', models.DateTimeField(verbose_name='Valid Until')),
                ('usage_limit', models.PositiveIntegerField(default=1000, verbose_name='Max Total Redemptions')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='Times Redeemed')),
                ('branch', models.ForeignKey(blank=True, help_text='Leave empty for all branches', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Offer / Coupon',
                'verbose_name_plural': 'Offers & Coupons',
                'ordering': ['-created_at'],
            },
        ),
    ]
