# Generated by Django 6.1 on 2026-09-09 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('menu', '0001_initial'),
        ('offers', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponusage',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='orders.order'),
        ),
        migrations.AddField(
            model_name='offer',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='core.restaurant'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='offers.offer'),
        ),
        migrations.AddField(
            model_name='offerbranch',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_offers', to='core.branch'),
        ),
        migrations.AddField(
            model_name='offerbranch',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicable_branches', to='offers.offer'),
        ),
        migrations.AddField(
            model_name='offermenuitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicable_offers', to='menu.menuitem'),
        ),
        migrations.AddField(
            model_name='offermenuitem',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeted_items', to='offers.offer'),
        ),
        migrations.AddConstraint(
            model_name='couponusage',
            constraint=models.CheckConstraint(condition=models.Q(('discount_availed__gte', 0)), name='coupon_discount_availed_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(condition=models.Q(('discount_value__gte', 0)), name='offer_discount_val_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(condition=models.Q(('min_order_value__gte', 0)), name='offer_min_order_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__gte', models.F('valid_from'))), name='offer_validity_window'),
        ),
        migrations.AddConstraint(
            model_name='offerbranch',
            constraint=models.UniqueConstraint(fields=('offer', 'branch'), name='unique_offer_branch'),
        ),
        migrations.AddConstraint(
            model_name='offermenuitem',
            constraint=models.UniqueConstraint(fields=('offer', 'menu_item'), name='unique_offer_menu_item'),
        ),
    ]
