# Generated by Django 5.1.15 on 2026-09-09 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_name', models.CharField(max_length=150)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('delivery_address', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('landmark', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('PENDING_RIDER', 'Pending Rider Assignment'), ('ASSIGNED', 'Rider Assigned'), ('PICKED_UP', 'Picked Up from Kitchen'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered to Customer'), ('FAILED', 'Delivery Failed / Returned')], db_index=True, default='PENDING_RIDER', max_length=25)),
                ('estimated_delivery_minutes', models.PositiveIntegerField(default=35)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_notes', models.TextField(blank=True)),
                ('assigned_rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliveries', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_dispatch', to='orders.order')),
            ],
            options={
                'verbose_name': 'Delivery Dispatch',
                'verbose_name_plural': 'Delivery Dispatches',
                'ordering': ['-created_at'],
            },
        ),
    ]
