# Generated by Django 6.1 on 2026-09-09 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_details', to='orders.order'),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='delivery_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='delivery.deliveryorder'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='delivery_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='delivery.deliveryorder'),
        ),
        migrations.AddField(
            model_name='deliverystatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverystatushistory',
            name='delivery_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='delivery.deliveryorder'),
        ),
        migrations.AddIndex(
            model_name='deliveryorder',
            index=models.Index(fields=['branch', 'status'], name='df_delivery_branch__4f9462_idx'),
        ),
    ]
