# Generated by Django 5.1.15 on 2026-09-09 05:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('kitchen_notes', models.CharField(blank=True, help_text='e.g., Less spicy, no onions, extra crispy', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COOKING', 'Cooking'), ('READY', 'Ready'), ('SERVED', 'Served')], default='PENDING', max_length=20)),
            ],
            options={
                'verbose_name': 'Order Line Item',
                'verbose_name_plural': 'Order Line Items',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Order #')),
                ('order_type', models.CharField(choices=[('DINE_IN', 'Dine-In'), ('TAKEAWAY', 'Takeaway / Counter'), ('DELIVERY', 'Home Delivery')], default='DINE_IN', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONFIRMED', 'Confirmed'), ('PREPARING', 'In Kitchen / Preparing'), ('READY', 'Ready for Serving / Pickup'), ('COMPLETED', 'Completed & Paid'), ('CANCELLED', 'Cancelled')], db_index=True, default='NEW', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal (₹)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Discount (₹)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='GST Tax (₹)')),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Grand Total (₹)')),
                ('is_paid', models.BooleanField(db_index=True, default=False, verbose_name='Payment Settled')),
                ('guest_count', models.PositiveIntegerField(default=1, verbose_name='Guest Count')),
                ('special_instructions', models.TextField(blank=True, verbose_name='Kitchen / Chef Notes')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Cancellation Reason')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('prep_started_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='branches.branch')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customers.customer')),
                ('server', models.ForeignKey(blank=True, help_text='Waiter or cashier taking the order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='served_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Restaurant Order',
                'verbose_name_plural': 'Restaurant Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
