# Generated by Django 5.1.15 on 2026-09-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('guest_name', models.CharField(max_length=120, verbose_name='Guest Name')),
                ('guest_phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('guest_email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('reservation_date', models.DateField(verbose_name='Booking Date')),
                ('reservation_time', models.TimeField(verbose_name='Booking Time')),
                ('guest_count', models.PositiveIntegerField(default=2, verbose_name='Guests Count')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('SEATED', 'Guest Seated'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No-Show')], db_index=True, default='PENDING', max_length=25, verbose_name='Status')),
                ('special_requests', models.TextField(blank=True, verbose_name='Special Requests / Dietary Preferences')),
            ],
            options={
                'verbose_name': 'Table Reservation',
                'verbose_name_plural': 'Table Reservations',
                'ordering': ['reservation_date', 'reservation_time'],
            },
        ),
    ]
