# Generated by Django 5.1.15 on 2026-09-09 05:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegisterSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=Decimal('2000.00'), max_digits=12, verbose_name='Opening Float Cash (₹)')),
                ('closing_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Counted Cash (₹)')),
                ('expected_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Expected Cash (₹)')),
                ('cash_discrepancy', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Difference / Shortage (₹)')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_sessions', to='branches.branch')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_registers', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_registers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cash Drawer Session',
                'verbose_name_plural': 'Cash Drawer Sessions',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='ZReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_date', models.DateField(db_index=True, verbose_name='Audit Date')),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('gross_sales', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Gross Sales (₹)')),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Discounts Given (₹)')),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='GST Tax Collected (₹)')),
                ('net_sales', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Net Revenue (₹)')),
                ('cash_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Cash Sales (₹)')),
                ('card_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Card Sales (₹)')),
                ('upi_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='UPI Sales (₹)')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Cash Outflow / Expenses (₹)')),
                ('net_drawer_balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Net Drawer Cash (₹)')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='z_reports', to='branches.branch')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_z_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Z-Report',
                'verbose_name_plural': 'Daily Z-Reports',
                'ordering': ['-report_date'],
                'unique_together': {('branch', 'report_date')},
            },
        ),
    ]
