# Generated by Django 6.1 on 2026-09-09 05:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchTaxConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('gstin', models.CharField(help_text='State-specific GSTIN', max_length=15)),
                ('state_code', models.CharField(help_text='2-digit state code: 36=TS, 37=AP, 29=KA, 33=TN, 32=KL', max_length=2)),
                ('is_sez', models.BooleanField(default=False)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_configuration', to='core.branch')),
            ],
            options={
                'verbose_name': 'Branch Tax Configuration',
                'verbose_name_plural': 'Branch Tax Configurations',
                'db_table': 'df_branch_tax_configs',
            },
        ),
        migrations.CreateModel(
            name='RestaurantTaxConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('pan_number', models.CharField(max_length=10)),
                ('is_composition_scheme', models.BooleanField(default=False)),
                ('default_service_charge_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_configuration', to='core.restaurant')),
            ],
            options={
                'verbose_name': 'Restaurant Tax Configuration',
                'verbose_name_plural': 'Restaurant Tax Configurations',
                'db_table': 'df_restaurant_tax_configs',
            },
        ),
        migrations.CreateModel(
            name='TaxCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('hsn_sac_code', models.CharField(default='996331', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_categories', to='core.restaurant')),
            ],
            options={
                'verbose_name': 'Tax Category',
                'verbose_name_plural': 'Tax Categories',
                'db_table': 'df_tax_categories',
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('component_name', models.CharField(choices=[('CGST', 'Central GST'), ('SGST', 'State GST'), ('IGST', 'Integrated GST'), ('VAT', 'Value Added Tax (Liquor)'), ('CESS', 'GST Compensation Cess')], max_length=20)),
                ('rate_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('tax_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='taxes.taxcategory')),
            ],
            options={
                'verbose_name': 'Tax Rate',
                'verbose_name_plural': 'Tax Rates',
                'db_table': 'df_tax_rates',
            },
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('rule_type', models.CharField(choices=[('INTRA_STATE', 'Intra-State (CGST + SGST)'), ('INTER_STATE', 'Inter-State (IGST)')], default='INTRA_STATE', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('tax_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='taxes.taxcategory')),
            ],
            options={
                'verbose_name': 'Tax Rule',
                'verbose_name_plural': 'Tax Rules',
                'db_table': 'df_tax_rules',
            },
        ),
        migrations.AddConstraint(
            model_name='taxcategory',
            constraint=models.UniqueConstraint(fields=('restaurant', 'code'), name='unique_tax_category_per_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='taxrate',
            constraint=models.CheckConstraint(condition=models.Q(('rate_percent__gte', 0), ('rate_percent__lte', 100)), name='tax_rate_valid_percentage'),
        ),
    ]
