# Generated by Django 6.1 on 2026-09-09 05:30

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('menu_type', models.CharField(choices=[('DINE_IN', 'Dine-in'), ('TAKEAWAY', 'Takeaway'), ('DELIVERY', 'Delivery'), ('BAR', 'Bar'), ('ALL', 'All Channels')], default='ALL', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='core.branch')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='core.restaurant')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'db_table': 'df_menus',
            },
        ),
        migrations.CreateModel(
            name='MenuAddon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='core.restaurant')),
            ],
            options={
                'verbose_name': 'Menu Addon',
                'verbose_name_plural': 'Menu Addons',
                'db_table': 'df_menu_addons',
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/categories/')),
                ('is_active', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='menu.menu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='menu.menucategory')),
            ],
            options={
                'verbose_name': 'Menu Category',
                'verbose_name_plural': 'Menu Categories',
                'db_table': 'df_menu_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('short_code', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('dietary_type', models.CharField(choices=[('VEG', 'Vegetarian'), ('NON_VEG', 'Non-Vegetarian'), ('EGG', 'Contains Egg'), ('VEGAN', 'Vegan'), ('JAIN', 'Jain Friendly')], db_index=True, default='VEG', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preparation_time_minutes', models.PositiveIntegerField(default=15)),
                ('calorie_count', models.PositiveIntegerField(blank=True, null=True)),
                ('hsn_code', models.CharField(default='996331', help_text='GST HSN/SAC Code for Restaurant Service', max_length=10)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('is_recommended', models.BooleanField(default=False)),
                ('is_spicy', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/items/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menucategory')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'db_table': 'df_menu_items',
            },
        ),
        migrations.CreateModel(
            name='MenuItemAddon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('max_quantity', models.PositiveSmallIntegerField(default=5)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menu.menuaddon')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_addons', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item Addon',
                'verbose_name_plural': 'Menu Item Addons',
                'db_table': 'df_menu_item_addons',
            },
        ),
        migrations.CreateModel(
            name='MenuVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sku', models.CharField(blank=True, max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Variant',
                'verbose_name_plural': 'Menu Variants',
                'db_table': 'df_menu_variants',
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_changes', to=settings.AUTH_USER_MODEL)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='menu.menuitem')),
                ('menu_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='menu.menuvariant')),
            ],
            options={
                'verbose_name': 'Price History',
                'verbose_name_plural': 'Price Histories',
                'db_table': 'df_price_history',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField()),
                ('prep_time_minutes', models.PositiveIntegerField(default=10)),
                ('cook_time_minutes', models.PositiveIntegerField(default=20)),
                ('yield_servings', models.PositiveIntegerField(default=1)),
                ('target_temperature_celsius', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('menu_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'db_table': 'df_recipes',
            },
        ),
        migrations.CreateModel(
            name='FoodIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity_required', models.DecimalField(decimal_places=3, help_text='Quantity in item measurement unit', max_digits=10)),
                ('unit_name', models.CharField(max_length=20)),
                ('wastage_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food_recipes', to='inventory.inventoryitem')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='menu.recipe')),
            ],
            options={
                'verbose_name': 'Food Ingredient (BOM)',
                'verbose_name_plural': 'Food Ingredients (BOM)',
                'db_table': 'df_food_ingredients',
            },
        ),
        migrations.AddConstraint(
            model_name='menuaddon',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='addon_price_non_negative'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['category', 'is_available'], name='df_menu_ite_categor_d0b70f_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['dietary_type', 'is_available'], name='df_menu_ite_dietary_cbb21e_idx'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.CheckConstraint(condition=models.Q(('base_price__gte', 0)), name='menu_item_base_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='menuitemaddon',
            constraint=models.UniqueConstraint(fields=('menu_item', 'addon'), name='unique_menu_item_addon'),
        ),
        migrations.AddConstraint(
            model_name='menuvariant',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='menu_variant_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='menuvariant',
            constraint=models.UniqueConstraint(fields=('menu_item', 'name'), name='unique_item_variant_name'),
        ),
        migrations.AddConstraint(
            model_name='foodingredient',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_required__gt', 0)), name='ingredient_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='foodingredient',
            constraint=models.CheckConstraint(condition=models.Q(('wastage_percentage__gte', 0), ('wastage_percentage__lte', 100)), name='ingredient_wastage_valid'),
        ),
    ]
