# Generated by Django 5.1.15 on 2026-09-09 05:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Menu Category',
                'verbose_name_plural': 'Menu Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Item Name')),
                ('code', models.CharField(blank=True, max_length=30, verbose_name='Short Code / SKU')),
                ('description', models.TextField(blank=True)),
                ('food_type', models.CharField(choices=[('VEG', 'Vegetarian'), ('NON_VEG', 'Non-Vegetarian'), ('EGG', 'Contains Egg'), ('VEGAN', 'Vegan')], default='VEG', max_length=20)),
                ('spice_level', models.CharField(choices=[('MILD', 'Mild'), ('MEDIUM', 'Medium'), ('SPICY', 'Spicy'), ('EXTRA_SPICY', 'Extra Spicy')], default='MEDIUM', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Base Price (₹)')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Est. Cost Price (₹)')),
                ('tax_rate_percent', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='GST Rate %')),
                ('preparation_time_minutes', models.PositiveIntegerField(default=15, verbose_name='Prep Time (Mins)')),
                ('is_available', models.BooleanField(db_index=True, default=True, verbose_name='Available for Ordering')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Chef Recommendation / Featured')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_items/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.category')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Addon Name')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Addon Price (₹)')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item Add-on',
                'verbose_name_plural': 'Menu Item Add-ons',
            },
        ),
        migrations.CreateModel(
            name='MenuItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, verbose_name='Variant Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Variant Price (₹)')),
                ('is_default', models.BooleanField(default=False)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item Variant',
                'verbose_name_plural': 'Menu Item Variants',
            },
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient_name', models.CharField(max_length=120, verbose_name='Raw Ingredient Name')),
                ('quantity_required', models.DecimalField(decimal_places=3, help_text='e.g., 0.250 for 250 grams or 0.100 for 100ml', max_digits=10, verbose_name='Quantity Required per Serving')),
                ('unit', models.CharField(default='kg', max_length=20, verbose_name='Unit of Measure')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_usages', to='inventory.ingredient')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'Recipe Ingredient',
                'verbose_name_plural': 'Recipe Ingredients',
            },
        ),
    ]
