# Generated by Django 5.1.15 on 2026-09-09 05:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Customer Name')),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('city', models.CharField(default='Hyderabad', max_length=100)),
                ('dietary_preferences', models.CharField(blank=True, help_text='e.g., Pure Veg, Jain, Low Spice, Gluten-Free', max_length=100)),
                ('special_notes', models.TextField(blank=True, verbose_name='Guest Notes / Anniversary / Allergies')),
                ('total_visits', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('last_visit_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
            },
        ),
    ]
