# Generated by Django 6.1 on 2026-09-09 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderhistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_history', to='orders.order'),
        ),
        migrations.AddField(
            model_name='customerpreference',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='customerreservationhistory',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_history_records', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='customerreservationhistory',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_history', to='tables.reservation'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['restaurant', 'phone'], name='df_customer_restaur_2d095f_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('restaurant', 'phone'), name='unique_customer_phone_per_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('total_spend__gte', 0)), name='customer_total_spend_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('loyalty_points__gte', 0)), name='customer_loyalty_points_non_negative'),
        ),
    ]
