# Generated by Django 5.1.15 on 2026-09-09 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Shift Name')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('break_duration_minutes', models.PositiveIntegerField(default=45, verbose_name='Break Allowance (Mins)')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Shift Template',
                'verbose_name_plural': 'Shift Templates',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ShiftRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, verbose_name='Roster Date')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('SWAPPED', 'Swapped'), ('ABSENT', 'Absent')], default='SCHEDULED', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_shifts', to='employees.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='shifts.shift')),
            ],
            options={
                'verbose_name': 'Shift Roster',
                'verbose_name_plural': 'Shift Rosters',
                'ordering': ['date', 'shift__start_time'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
