# Generated by Django 5.1.15 on 2026-09-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseBackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=150)),
                ('file_path', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('status', models.CharField(default='SUCCESS', max_length=20)),
            ],
            options={
                'verbose_name': 'Database Backup Record',
                'verbose_name_plural': 'Database Backup Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
