# Generated by Django 5.1.15 on 2026-09-09 05:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('customers', '0001_initial'),
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Invoice #')),
                ('restaurant_name', models.CharField(max_length=200)),
                ('restaurant_gstin', models.CharField(max_length=15, verbose_name='GSTIN')),
                ('fssai_number', models.CharField(max_length=20, verbose_name='FSSAI Lic #')),
                ('branch_address', models.TextField()),
                ('taxable_subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Taxable Value (₹)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Discount (₹)')),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='CGST (₹)')),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='SGST (₹)')),
                ('igst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='IGST (₹)')),
                ('total_tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total GST (₹)')),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Invoice Grand Total (₹)')),
                ('is_paid', models.BooleanField(db_index=True, default=False)),
                ('payment_method', models.CharField(default='PENDING', max_length=50, verbose_name='Payment Method')),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='branches.branch')),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_invoices', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='customers.customer')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='orders.order')),
            ],
            options={
                'verbose_name': 'Tax Invoice',
                'verbose_name_plural': 'Tax Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_name', models.CharField(max_length=150)),
                ('sac_code', models.CharField(default='996331', max_length=20, verbose_name='SAC Code')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rate (₹)')),
                ('item_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total (₹)')),
                ('tax_rate_percent', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='GST %')),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Item',
                'verbose_name_plural': 'Invoice Items',
            },
        ),
    ]
