# Generated by Django 6.1 on 2026-09-09 05:30

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=60, unique=True)),
                ('fiscal_year', models.CharField(db_index=True, max_length=10)),
                ('invoice_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('customer_name', models.CharField(blank=True, max_length=150)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('customer_gstin', models.CharField(blank=True, max_length=15)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('round_off', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially Paid'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='ISSUED', max_length=20)),
                ('qr_code_data', models.TextField(blank=True, help_text='B2C UPI / GST e-Invoice payload')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'df_invoices',
            },
        ),
        migrations.CreateModel(
            name='InvoiceDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(max_length=150)),
                ('rate_or_flat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Invoice Discount',
                'verbose_name_plural': 'Invoice Discounts',
                'db_table': 'df_invoice_discounts',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('item_name', models.CharField(max_length=150)),
                ('hsn_sac_code', models.CharField(default='996331', max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Invoice Item',
                'verbose_name_plural': 'Invoice Items',
                'db_table': 'df_invoice_items',
            },
        ),
        migrations.CreateModel(
            name='InvoiceNumberSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('fiscal_year', models.CharField(help_text='e.g. 2026-27', max_length=10)),
                ('prefix', models.CharField(default='INV', max_length=10)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Invoice Number Sequence',
                'verbose_name_plural': 'Invoice Number Sequences',
                'db_table': 'df_invoice_sequences',
            },
        ),
        migrations.CreateModel(
            name='InvoiceTax',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tax_category_name', models.CharField(max_length=100)),
                ('component_name', models.CharField(max_length=20)),
                ('rate_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Invoice Tax Breakdown',
                'verbose_name_plural': 'Invoice Tax Breakdowns',
                'db_table': 'df_invoice_taxes',
            },
        ),
    ]
