# Generated by Django 6.1 on 2026-09-09 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_initial'),
        ('core', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='orders.order'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.restaurant'),
        ),
        migrations.AddField(
            model_name='invoicediscount',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='invoicenumbersequence',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_sequences', to='core.branch'),
        ),
        migrations.AddField(
            model_name='invoicetax',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_breakdowns', to='billing.invoice'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['branch', 'invoice_date'], name='df_invoices_branch__b55d71_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['branch', 'status', 'invoice_date'], name='df_invoices_branch__574475_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='invoice_subtotal_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('taxable_amount__gte', 0)), name='invoice_taxable_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('grand_total__gte', 0)), name='invoice_grand_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('cgst_amount__gte', 0)), name='invoice_cgst_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('sgst_amount__gte', 0)), name='invoice_sgst_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('igst_amount__gte', 0)), name='invoice_igst_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inv_item_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='inv_item_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='inv_item_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='invoicenumbersequence',
            constraint=models.UniqueConstraint(fields=('branch', 'fiscal_year', 'prefix'), name='unique_invoice_seq_per_branch_fy'),
        ),
    ]
