# Generated by Django 6.1 on 2026-09-09 05:30

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('points_required', models.PositiveIntegerField()),
                ('reward_type', models.CharField(choices=[('FREE_ITEM', 'Free Menu Item'), ('BILL_DISCOUNT', 'Bill Discount Voucher'), ('SPECIAL_PERK', 'Special Dining Perk')], default='BILL_DISCOUNT', max_length=20)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Loyalty Reward',
                'verbose_name_plural': 'Loyalty Rewards',
                'db_table': 'df_rewards',
            },
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('points_spent', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('REDEEMED', 'Redeemed'), ('CANCELLED', 'Cancelled')], default='REDEEMED', max_length=20)),
                ('redeemed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Reward Redemption',
                'verbose_name_plural': 'Reward Redemptions',
                'db_table': 'df_reward_redemptions',
            },
        ),
        migrations.CreateModel(
            name='CustomerTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('min_lifetime_spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('points_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('benefits_description', models.TextField(blank=True)),
                ('badge_color', models.CharField(default='#CD7F32', max_length=20)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_tiers', to='core.restaurant')),
            ],
            options={
                'verbose_name': 'Customer Tier',
                'verbose_name_plural': 'Customer Tiers',
                'db_table': 'df_customer_tiers',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('current_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('lifetime_earned_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('lifetime_redeemed_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('last_activity_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_account', to='customers.customer')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='loyalty.customertier')),
            ],
            options={
                'verbose_name': 'Loyalty Account',
                'verbose_name_plural': 'Loyalty Accounts',
                'db_table': 'df_loyalty_accounts',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('EARNED', 'Points Earned from Purchase'), ('REDEEMED', 'Points Redeemed on Bill'), ('BONUS', 'Bonus Points Credited'), ('EXPIRED', 'Points Expired'), ('ADJUSTMENT', 'Manual Adjustment')], db_index=True, max_length=20)),
                ('points', models.DecimalField(decimal_places=2, help_text='+ for credit, - for debit', max_digits=10)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.loyaltyaccount')),
            ],
            options={
                'verbose_name': 'Loyalty Transaction',
                'verbose_name_plural': 'Loyalty Transactions',
                'db_table': 'df_loyalty_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
