# Generated by Django 6.1 on 2026-09-09 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('loyalty', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltytransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='reward',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='core.restaurant'),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='loyalty.loyaltyaccount'),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_redemptions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='loyalty.reward'),
        ),
        migrations.AddConstraint(
            model_name='customertier',
            constraint=models.UniqueConstraint(fields=('restaurant', 'name'), name='unique_tier_name_per_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='customertier',
            constraint=models.CheckConstraint(condition=models.Q(('min_lifetime_spend__gte', 0)), name='tier_min_spend_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='customertier',
            constraint=models.CheckConstraint(condition=models.Q(('points_multiplier__gt', 0)), name='tier_multiplier_positive'),
        ),
        migrations.AddConstraint(
            model_name='loyaltyaccount',
            constraint=models.CheckConstraint(condition=models.Q(('current_points__gte', 0)), name='loyalty_points_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.CheckConstraint(condition=models.Q(('points_required__gt', 0)), name='reward_points_positive'),
        ),
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='reward_discount_non_negative'),
        ),
    ]
