# Generated by Django 5.1.15 on 2026-09-09 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_number', models.CharField(max_length=50, verbose_name='KOT #')),
                ('station', models.CharField(choices=[('ALL', 'Main Kitchen / All Stations'), ('BIRYANI_CURRY', 'Biryani & Curry Section'), ('TANDOOR_GRILL', 'Tandoor & Starters Station'), ('DOSA_SOUTH', 'South Indian & Tiffin Station'), ('BEVERAGES', 'Beverages & Mocktails'), ('DESSERT', 'Dessert Station')], default='ALL', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Cook'), ('PREPARING', 'Cooking / In Progress'), ('READY', 'Ready for Expeditor'), ('BUMPED', 'Served / Cleared')], db_index=True, default='PENDING', max_length=20)),
                ('expected_prep_minutes', models.PositiveIntegerField(default=15, verbose_name='Expected SLA (Mins)')),
                ('started_cooking_at', models.DateTimeField(blank=True, null=True)),
                ('completed_cooking_at', models.DateTimeField(blank=True, null=True)),
                ('bumped_at', models.DateTimeField(blank=True, null=True)),
                ('bumped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bumped_tickets', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_tickets', to='orders.order')),
            ],
            options={
                'verbose_name': 'Kitchen Ticket (KOT)',
                'verbose_name_plural': 'Kitchen Tickets (KOTs)',
                'ordering': ['created_at'],
            },
        ),
    ]
