# Generated by Django 6.1 on 2026-09-09 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('kitchen', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_orders', to='orders.order'),
        ),
        migrations.AddField(
            model_name='kitchenorderitem',
            name='kitchen_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kitchen.kitchenorder'),
        ),
        migrations.AddField(
            model_name='kitchenorderitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_items', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='kitchenstation',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_stations', to='core.branch'),
        ),
        migrations.AddField(
            model_name='kitchenorder',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_orders', to='kitchen.kitchenstation'),
        ),
        migrations.AddField(
            model_name='kitchenstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kitchenstatushistory',
            name='kitchen_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='kitchen.kitchenorder'),
        ),
        migrations.AddField(
            model_name='preparationtimer',
            name='kitchen_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='kitchen.kitchenorder'),
        ),
        migrations.AddField(
            model_name='preparationtimer',
            name='kitchen_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='kitchen.kitchenorderitem'),
        ),
        migrations.AddConstraint(
            model_name='kitchenorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='kot_item_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='kitchenstation',
            constraint=models.UniqueConstraint(fields=('branch', 'code'), name='unique_station_code_per_branch'),
        ),
        migrations.AddIndex(
            model_name='kitchenorder',
            index=models.Index(fields=['branch', 'status', 'created_at'], name='df_kitchen__branch__95214c_idx'),
        ),
    ]
