# Generated by Django 6.1 on 2026-09-09 05:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.TextField()),
                ('value_type', models.CharField(choices=[('STRING', 'String'), ('INT', 'Integer'), ('FLOAT', 'Float'), ('BOOLEAN', 'Boolean'), ('JSON', 'JSON Object')], default='STRING', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_encrypted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'db_table': 'df_system_settings',
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('backup_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('backup_type', models.CharField(choices=[('FULL_SQLITE', 'Full SQLite Backup'), ('POSTGRES_DUMP', 'PostgreSQL pg_dump'), ('SCHEMA_ONLY', 'Schema Only'), ('DATA_FIXTURES', 'Data Fixtures (JSON)')], default='FULL_SQLITE', max_length=30)),
                ('file_path', models.CharField(max_length=255)),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('RESTORED', 'Restored')], db_index=True, default='IN_PROGRESS', max_length=20)),
                ('restore_status', models.CharField(choices=[('NOT_RESTORED', 'Not Restored'), ('RESTORE_VERIFIED', 'Restore Verified'), ('RESTORE_FAILED', 'Restore Failed')], default='NOT_RESTORED', max_length=30)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Database Backup Record',
                'verbose_name_plural': 'Database Backup Records',
                'db_table': 'df_backup_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('email_host', models.CharField(blank=True, max_length=150)),
                ('email_port', models.PositiveIntegerField(default=587)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_sender', models.EmailField(blank=True, max_length=254)),
                ('sms_sender_id', models.CharField(blank=True, help_text='DLT registered header for India SMS', max_length=20)),
                ('is_sms_active', models.BooleanField(default=False)),
                ('is_whatsapp_active', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='core.branch')),
            ],
            options={
                'verbose_name': 'Notification Setting',
                'verbose_name_plural': 'Notification Settings',
                'db_table': 'df_notification_settings',
            },
        ),
        migrations.CreateModel(
            name='BranchSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_settings', to='core.branch')),
            ],
            options={
                'verbose_name': 'Branch Setting',
                'verbose_name_plural': 'Branch Settings',
                'db_table': 'df_branch_custom_settings',
                'constraints': [models.UniqueConstraint(fields=('branch', 'key'), name='unique_branch_setting_key')],
            },
        ),
        migrations.CreateModel(
            name='RestaurantSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_settings', to='core.restaurant')),
            ],
            options={
                'verbose_name': 'Restaurant Setting',
                'verbose_name_plural': 'Restaurant Settings',
                'db_table': 'df_restaurant_custom_settings',
                'constraints': [models.UniqueConstraint(fields=('restaurant', 'key'), name='unique_restaurant_setting_key')],
            },
        ),
    ]
