# Generated by Django 5.1.15 on 2026-09-09 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount Paid (₹)')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI (Google Pay / PhonePe / Paytm)'), ('CARD', 'Credit / Debit Card'), ('SPLIT', 'Split Payment')], default='CASH', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Settled / Successful'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='SUCCESS', max_length=20)),
                ('transaction_reference', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Transaction Ref / UTR')),
                ('upi_vpa', models.CharField(blank=True, max_length=100, verbose_name='Payer UPI VPA')),
                ('card_last4', models.CharField(blank=True, max_length=4, verbose_name='Card Last 4 Digits')),
                ('card_network', models.CharField(blank=True, help_text='Visa, Mastercard, RuPay', max_length=30, verbose_name='Card Network')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_payments', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.invoice')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Payment Record',
                'verbose_name_plural': 'Payment Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
