# Generated by Django 5.1.15 on 2026-09-09 05:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('company_name', models.CharField(db_index=True, max_length=150, verbose_name='Supplier / Company Name')),
                ('gstin', models.CharField(blank=True, help_text='15-digit GST Identification Number', max_length=15, verbose_name='GSTIN')),
                ('fssai_number', models.CharField(blank=True, max_length=20, verbose_name='FSSAI Lic #')),
                ('contact_person', models.CharField(max_length=100, verbose_name='Contact Person')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('address', models.TextField(verbose_name='Office / Warehouse Address')),
                ('city', models.CharField(default='Hyderabad', max_length=100)),
                ('state', models.CharField(default='Telangana', max_length=100)),
                ('payment_terms', models.CharField(default='NET_15', help_text='e.g., ADVANCE, COD, NET_15, NET_30', max_length=50, verbose_name='Payment Terms')),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, verbose_name='IFSC Code')),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Outstanding (₹)')),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('4.5'), max_digits=3, verbose_name='Performance Rating (1-5)')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Supplier / Vendor',
                'verbose_name_plural': 'Suppliers & Vendors',
                'ordering': ['company_name'],
            },
        ),
    ]
