# Generated by Django 5.1.15 on 2026-09-09 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Section Name')),
                ('floor_number', models.IntegerField(default=0, verbose_name='Floor Level')),
                ('description', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_sections', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Floor Section',
                'verbose_name_plural': 'Floor Sections',
                'ordering': ['floor_number', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('table_number', models.CharField(max_length=30, verbose_name='Table #')),
                ('seating_capacity', models.PositiveIntegerField(default=4, verbose_name='Capacity')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved'), ('CLEANING', 'Cleaning'), ('MAINTENANCE', 'Maintenance')], db_index=True, default='AVAILABLE', max_length=20, verbose_name='Occupancy Status')),
                ('pos_x', models.IntegerField(default=0, verbose_name='Grid X Position')),
                ('pos_y', models.IntegerField(default=0, verbose_name='Grid Y Position')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='branches.branch')),
                ('current_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupied_table', to='orders.order')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='tables.floorsection')),
            ],
            options={
                'verbose_name': 'Restaurant Table',
                'verbose_name_plural': 'Restaurant Tables',
                'ordering': ['table_number'],
                'unique_together': {('branch', 'table_number')},
            },
        ),
    ]
