# Generated by Django 6.1 on 2026-09-09 05:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reservation_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('reservation_time', models.DateTimeField(db_index=True)),
                ('party_size', models.PositiveSmallIntegerField(default=2)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('CONFIRMED', 'Confirmed'), ('SEATED', 'Seated'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No-Show')], db_index=True, default='CONFIRMED', max_length=20)),
                ('special_requests', models.TextField(blank=True)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'db_table': 'df_reservations',
            },
        ),
        migrations.CreateModel(
            name='ReservationGuest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('guest_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_primary', models.BooleanField(default=False)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='tables.reservation')),
            ],
            options={
                'verbose_name': 'Reservation Guest',
                'verbose_name_plural': 'Reservation Guests',
                'db_table': 'df_reservation_guests',
            },
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('table_number', models.CharField(max_length=20)),
                ('seating_capacity', models.PositiveSmallIntegerField(default=4)),
                ('min_capacity', models.PositiveSmallIntegerField(default=1)),
                ('shape', models.CharField(choices=[('SQUARE', 'Square'), ('ROUND', 'Round'), ('RECTANGLE', 'Rectangle')], default='RECTANGLE', max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved'), ('BILLED', 'Billed'), ('CLEANING', 'Cleaning'), ('OUT_OF_SERVICE', 'Out of Service')], db_index=True, default='AVAILABLE', max_length=20)),
                ('qr_code_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='core.branch')),
            ],
            options={
                'verbose_name': 'Restaurant Table',
                'verbose_name_plural': 'Restaurant Tables',
                'db_table': 'df_restaurant_tables',
            },
        ),
        migrations.CreateModel(
            name='TableAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_assignments', to='tables.reservation')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tables.restauranttable')),
                ('waiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_assignments', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Table Assignment',
                'verbose_name_plural': 'Table Assignments',
                'db_table': 'df_table_assignments',
            },
        ),
        migrations.CreateModel(
            name='TableSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('floor', models.CharField(default='Ground Floor', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_sections', to='core.branch')),
            ],
            options={
                'verbose_name': 'Table Section',
                'verbose_name_plural': 'Table Sections',
                'db_table': 'df_table_sections',
            },
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='tables.tablesection'),
        ),
        migrations.CreateModel(
            name='TableStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('previous_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_status_changes', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='tables.restauranttable')),
            ],
            options={
                'verbose_name': 'Table Status Log',
                'verbose_name_plural': 'Table Status Logs',
                'db_table': 'df_table_status_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['branch', 'reservation_time', 'status'], name='df_reservat_branch__be6823_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('party_size__gt', 0)), name='reservation_party_size_positive'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_amount__gte', 0)), name='reservation_deposit_non_negative'),
        ),
        migrations.AddIndex(
            model_name='tableassignment',
            index=models.Index(fields=['table', 'status'], name='df_table_as_table_i_82bab4_idx'),
        ),
        migrations.AddIndex(
            model_name='tableassignment',
            index=models.Index(fields=['waiter', 'status'], name='df_table_as_waiter__0ba744_idx'),
        ),
        migrations.AddConstraint(
            model_name='tablesection',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='unique_section_per_branch'),
        ),
        migrations.AddIndex(
            model_name='restauranttable',
            index=models.Index(fields=['branch', 'status'], name='df_restaura_branch__70816a_idx'),
        ),
        migrations.AddConstraint(
            model_name='restauranttable',
            constraint=models.UniqueConstraint(fields=('branch', 'table_number'), name='unique_table_per_branch'),
        ),
        migrations.AddConstraint(
            model_name='restauranttable',
            constraint=models.CheckConstraint(condition=models.Q(('seating_capacity__gt', 0)), name='table_seating_capacity_positive'),
        ),
        migrations.AddConstraint(
            model_name='restauranttable',
            constraint=models.CheckConstraint(condition=models.Q(('seating_capacity__gte', models.F('min_capacity'))), name='capacity_gte_min_capacity'),
        ),
    ]
