# Generated by Django 5.1.15 on 2026-09-09 05:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Ingredient Category',
                'verbose_name_plural': 'Ingredient Categories',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Ingredient Name')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='SKU / Code')),
                ('unit', models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('L', 'Liter (L)'), ('ml', 'Milliliter (ml)'), ('pcs', 'Pieces (pcs)'), ('pack', 'Pack (pack)'), ('dz', 'Dozen (dz)')], default='kg', max_length=10, verbose_name='Unit')),
                ('current_stock', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Current Stock Level')),
                ('minimum_stock_level', models.DecimalField(decimal_places=3, default=Decimal('10.000'), max_digits=12, verbose_name='Reorder / Low Stock Level')),
                ('optimal_stock_level', models.DecimalField(decimal_places=3, default=Decimal('100.000'), max_digits=12, verbose_name='Max / Optimal Stock')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Unit Cost (₹)')),
                ('batch_number', models.CharField(blank=True, max_length=50, verbose_name='Batch #')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='branches.branch')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='inventory.ingredientcategory')),
            ],
            options={
                'verbose_name': 'Raw Ingredient',
                'verbose_name_plural': 'Raw Ingredients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('OPENING_STOCK', 'Opening Stock'), ('PURCHASE_RECEIPT', 'Purchase Inward'), ('ORDER_CONSUMPTION', 'Recipe Consumption'), ('WASTE_SPOILAGE', 'Waste / Spoilage'), ('AUDIT_ADJUSTMENT', 'Physical Count Adjustment'), ('BRANCH_TRANSFER', 'Branch Transfer')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Positive for intake, negative for consumption/waste', max_digits=12, verbose_name='Quantity Delta (+ or -)')),
                ('stock_before', models.DecimalField(decimal_places=3, max_digits=12)),
                ('stock_after', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reference_id', models.CharField(blank=True, max_length=100, verbose_name='Order # / PO # / Reason')),
                ('notes', models.TextField(blank=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.ingredient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-created_at'],
            },
        ),
    ]
