# Generated by Django 6.1 on 2026-09-09 05:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('is_base_unit', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unit of Measurement',
                'verbose_name_plural': 'Units of Measurement',
                'db_table': 'df_units',
            },
        ),
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_categories', to='core.restaurant')),
            ],
            options={
                'verbose_name': 'Inventory Category',
                'verbose_name_plural': 'Inventory Categories',
                'db_table': 'df_inventory_categories',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('item_code', models.CharField(db_index=True, max_length=50)),
                ('reorder_level', models.DecimalField(decimal_places=3, default=10.0, max_digits=12)),
                ('safety_stock', models.DecimalField(decimal_places=3, default=5.0, max_digits=12)),
                ('current_cost_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_perishable', models.BooleanField(default=False)),
                ('shelf_life_days', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventorycategory')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='core.restaurant')),
                ('primary_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='inventory.unit')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'db_table': 'df_inventory_items',
            },
        ),
        migrations.CreateModel(
            name='InventoryAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('alert_type', models.CharField(choices=[('LOW_STOCK', 'Low Stock Threshold'), ('OUT_OF_STOCK', 'Out of Stock'), ('NEAR_EXPIRY', 'Near Expiry Date'), ('EXPIRED', 'Expired Stock')], db_index=True, max_length=30)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_alerts', to='core.branch')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.inventoryitem')),
            ],
            options={
                'verbose_name': 'Inventory Alert',
                'verbose_name_plural': 'Inventory Alerts',
                'db_table': 'df_inventory_alerts',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('culinary_name', models.CharField(max_length=150)),
                ('storage_temperature_celsius', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('yield_percentage', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('allergens', models.CharField(blank=True, max_length=255)),
                ('inventory_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_details', to='inventory.inventoryitem')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'db_table': 'df_ingredients',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity_on_hand', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('reserved_quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('available_quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('last_stock_take_date', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='core.branch')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_stocks', to='inventory.inventoryitem')),
            ],
            options={
                'verbose_name': 'Stock Level',
                'verbose_name_plural': 'Stock Levels',
                'db_table': 'df_stocks',
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('adjustment_type', models.CharField(choices=[('INCREASE', 'Increase'), ('DECREASE', 'Decrease')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reason', models.CharField(choices=[('DAMAGE', 'Damaged Stock'), ('EXPIRED', 'Expired Stock'), ('AUDIT_VARIANCE', 'Audit / Physical Count Variance'), ('THEFT', 'Theft / Pilferage'), ('OTHER', 'Other Reason')], max_length=30)),
                ('cost_impact', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='core.branch')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.inventoryitem')),
            ],
            options={
                'verbose_name': 'Stock Adjustment',
                'verbose_name_plural': 'Stock Adjustments',
                'db_table': 'df_stock_adjustments',
            },
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('batch_number', models.CharField(max_length=50)),
                ('received_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('purchase_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('initial_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('remaining_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_batches', to='core.branch')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.inventoryitem')),
            ],
            options={
                'verbose_name': 'Stock Batch',
                'verbose_name_plural': 'Stock Batches',
                'db_table': 'df_stock_batches',
            },
        ),
        migrations.CreateModel(
            name='ExpiryRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('expired_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('recorded_date', models.DateField(default=django.utils.timezone.now)),
                ('action_taken', models.CharField(choices=[('DISCARDED', 'Discarded'), ('DONATED', 'Donated'), ('RETURNED', 'Returned to Vendor')], max_length=30)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_records', to='inventory.stockbatch')),
            ],
            options={
                'verbose_name': 'Expiry Record',
                'verbose_name_plural': 'Expiry Records',
                'db_table': 'df_expiry_records',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('movement_type', models.CharField(choices=[('PURCHASE_RECEIPT', 'Purchase Receipt'), ('RECIPE_CONSUMPTION', 'Recipe Consumption'), ('WASTAGE', 'Wastage / Spoilage'), ('ADJUSTMENT_ADD', 'Adjustment (Addition)'), ('ADJUSTMENT_SUB', 'Adjustment (Deduction)'), ('RETURN_TO_SUPPLIER', 'Return to Supplier'), ('BRANCH_TRANSFER_IN', 'Branch Transfer In'), ('BRANCH_TRANSFER_OUT', 'Branch Transfer Out')], db_index=True, max_length=30)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='+ for addition, - for reduction', max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=3, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reference_id', models.CharField(blank=True, help_text='e.g. Order #, PO #, GRN #', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.stockbatch')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventoryitem')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'db_table': 'df_stock_movements',
            },
        ),
        migrations.CreateModel(
            name='WasteRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reason', models.TextField()),
                ('cost_impact', models.DecimalField(decimal_places=2, max_digits=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_records', to='core.branch')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_records', to='inventory.inventoryitem')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Waste Record',
                'verbose_name_plural': 'Waste Records',
                'db_table': 'df_waste_records',
            },
        ),
        migrations.AddConstraint(
            model_name='inventorycategory',
            constraint=models.UniqueConstraint(fields=('restaurant', 'code'), name='unique_inv_category_per_restaurant'),
        ),
        migrations.AddIndex(
            model_name='inventoryalert',
            index=models.Index(fields=['branch', 'is_resolved'], name='df_inventor_branch__9c6555_idx'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.CheckConstraint(condition=models.Q(('yield_percentage__gt', 0), ('yield_percentage__lte', 100)), name='ingredient_yield_valid_percent'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['branch', 'inventory_item'], name='df_stocks_branch__ae6bf2_idx'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('branch', 'inventory_item'), name='unique_stock_per_branch_item'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_on_hand__gte', 0)), name='stock_on_hand_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('available_quantity__gte', 0)), name='stock_available_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='adjustment_qty_positive'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['branch', 'expiry_date'], name='df_stock_ba_branch__9443ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_quantity__gte', 0)), name='batch_remaining_qty_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_unit_price__gte', 0)), name='batch_unit_price_non_negative'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['branch', 'inventory_item', 'created_at'], name='df_stock_mo_branch__62b376_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', 'created_at'], name='df_stock_mo_movemen_35bab2_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['restaurant', 'category', 'is_active'], name='df_inventor_restaur_c3935c_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('restaurant', 'item_code'), name='unique_item_code_per_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('reorder_level__gte', 0)), name='inv_reorder_level_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('current_cost_per_unit__gte', 0)), name='inv_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='wasterecord',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='waste_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='wasterecord',
            constraint=models.CheckConstraint(condition=models.Q(('cost_impact__gte', 0)), name='waste_cost_non_negative'),
        ),
    ]
