# Generated by Django 5.1.15 on 2026-09-09 05:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('sac_code', models.CharField(default='996331', help_text='SAC 9963 for Restaurant Services', max_length=20, verbose_name='SAC / HSN Code')),
                ('total_rate_percent', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='Total GST Rate %')),
                ('cgst_rate_percent', models.DecimalField(decimal_places=2, default=Decimal('2.50'), max_digits=5, verbose_name='CGST Rate %')),
                ('sgst_rate_percent', models.DecimalField(decimal_places=2, default=Decimal('2.50'), max_digits=5, verbose_name='SGST Rate %')),
                ('igst_rate_percent', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='IGST Rate %')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tax Category',
                'verbose_name_plural': 'Tax Categories',
            },
        ),
    ]
