# Generated by Django 5.1.15 on 2026-09-09 05:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, verbose_name='Attendance Date')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='Check-in Time')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='Check-out Time')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late Arrival'), ('HALF_DAY', 'Half Day'), ('ABSENT', 'Absent (LOP)'), ('ON_LEAVE', 'Approved Leave'), ('WEEKLY_OFF', 'Weekly Off')], db_index=True, default='PRESENT', max_length=20)),
                ('late_minutes', models.PositiveIntegerField(default=0, verbose_name='Late Arrival (Minutes)')),
                ('early_departure_minutes', models.PositiveIntegerField(default=0, verbose_name='Early Departure (Minutes)')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Overtime (Hours)')),
                ('remarks', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date', 'employee__employee_id'],
            },
        ),
    ]
