# Generated by Django 6.1 on 2026-09-09 05:30

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create Object'), ('UPDATE', 'Update Object'), ('DELETE', 'Delete / Soft Delete'), ('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('PERMISSION_CHANGE', 'Permission Change'), ('PAYMENT', 'Payment Captured'), ('REFUND', 'Refund Processed'), ('INVENTORY_ADJUSTMENT', 'Inventory Adjustment'), ('PAYROLL_APPROVAL', 'Payroll Approval')], db_index=True, max_length=30)),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.CharField(db_index=True, max_length=100)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'df_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('login_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('SUCCESS', 'Successful Login'), ('FAILED', 'Failed Password'), ('LOCKED', 'Account Locked')], default='SUCCESS', max_length=20)),
            ],
            options={
                'verbose_name': 'Login History',
                'verbose_name_plural': 'Login Histories',
                'db_table': 'df_login_histories',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('FAILED_LOGIN', 'Failed Login Attempt'), ('BRUTE_FORCE_BLOCKED', 'Brute Force IP Blocked'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Resource Access'), ('PASSWORD_CHANGED', 'Password Changed'), ('SESSION_HIJACK_SUSPECT', 'Suspicious Session Change')], db_index=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('INFO', 'Informational'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Security Event',
                'verbose_name_plural': 'Security Events',
                'db_table': 'df_security_events',
                'ordering': ['-timestamp'],
            },
        ),
    ]
