# Generated by Django 5.1.15 on 2026-09-09 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CREATE', 'Created Entity'), ('UPDATE', 'Updated Record'), ('DELETE', 'Deleted Entity'), ('PRICE_CHANGE', 'Menu Price Modified'), ('ORDER_CANCEL', 'Order Cancelled'), ('REFUND_APPROVE', 'Refund Approved'), ('STOCK_ADJUST', 'Inventory Stock Adjusted'), ('PAYROLL_RUN', 'Monthly Payroll Generated')], db_index=True, max_length=30)),
                ('module_name', models.CharField(db_index=True, max_length=50, verbose_name='App / Module')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='Target ID')),
                ('object_repr', models.CharField(max_length=255, verbose_name='Object Summary')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('old_values', models.JSONField(blank=True, default=dict, verbose_name='Previous State')),
                ('new_values', models.JSONField(blank=True, default=dict, verbose_name='New State')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
