# Generated by Django 6.1 on 2026-09-09 05:30

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(db_index=True)),
                ('new_customers_count', models.PositiveIntegerField(default=0)),
                ('repeat_customers_count', models.PositiveIntegerField(default=0)),
                ('average_visit_interval_days', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('churn_risk_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Customer Analytic',
                'verbose_name_plural': 'Customer Analytics',
                'db_table': 'df_customer_analytics',
            },
        ),
        migrations.CreateModel(
            name='DailySalesSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(db_index=True)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_gross_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('total_discounts', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_tax_collected', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_net_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('dine_in_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('takeaway_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('delivery_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cash_collected', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('upi_collected', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('card_collected', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('avg_order_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Daily Sales Snapshot',
                'verbose_name_plural': 'Daily Sales Snapshots',
                'db_table': 'df_daily_sales_snapshots',
            },
        ),
        migrations.CreateModel(
            name='DemandPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('prediction_date', models.DateField(db_index=True)),
                ('predicted_quantity', models.PositiveIntegerField()),
                ('confidence_low', models.PositiveIntegerField(default=0)),
                ('confidence_high', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Demand Prediction',
                'verbose_name_plural': 'Demand Predictions',
                'db_table': 'df_demand_predictions',
            },
        ),
        migrations.CreateModel(
            name='ExpenseAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
            ],
            options={
                'verbose_name': 'Expense Analytic',
                'verbose_name_plural': 'Expense Analytics',
                'db_table': 'df_expense_analytics',
            },
        ),
        migrations.CreateModel(
            name='InventoryAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(db_index=True)),
                ('total_stock_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('waste_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('consumption_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('stock_turnover_ratio', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
            options={
                'verbose_name': 'Inventory Analytic',
                'verbose_name_plural': 'Inventory Analytics',
                'db_table': 'df_inventory_analytics',
            },
        ),
        migrations.CreateModel(
            name='MonthlySalesSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
            options={
                'verbose_name': 'Monthly Sales Snapshot',
                'verbose_name_plural': 'Monthly Sales Snapshots',
                'db_table': 'df_monthly_sales_snapshots',
            },
        ),
        migrations.CreateModel(
            name='ProductSalesAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(db_index=True)),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cost_of_goods_sold', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gross_margin', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Product Sales Analytic',
                'verbose_name_plural': 'Product Sales Analytics',
                'db_table': 'df_product_sales_analytics',
            },
        ),
        migrations.CreateModel(
            name='ProfitAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(db_index=True)),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('cogs', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('operating_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('profit_margin_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Profit Analytic',
                'verbose_name_plural': 'Profit Analytics',
                'db_table': 'df_profit_analytics',
            },
        ),
    ]
