# Generated by Django 5.1.15 on 2026-09-09 05:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Gross Revenue (₹)')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Expenses (₹)')),
                ('net_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Net Profit (₹)')),
                ('order_count', models.PositiveIntegerField(default=0, verbose_name='Total Orders')),
                ('guest_covers', models.PositiveIntegerField(default=0, verbose_name='Total Guests Served')),
                ('average_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='AOV (₹)')),
                ('revpash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='RevPASH (₹/Seat-Hour)')),
                ('table_turnover_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Table Turnover Rate')),
                ('food_cost_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Food Cost (COGS) %')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Daily Analytics Snapshot',
                'verbose_name_plural': 'Daily Analytics Snapshots',
                'ordering': ['-date'],
                'unique_together': {('branch', 'date')},
            },
        ),
    ]
