# Generated by Django 6.1 on 2026-09-09 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('core', '0001_initial'),
        ('expenses', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeranalytics',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_analytics', to='core.branch'),
        ),
        migrations.AddField(
            model_name='dailysalessnapshot',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sales_snapshots', to='core.branch'),
        ),
        migrations.AddField(
            model_name='demandprediction',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_predictions', to='core.branch'),
        ),
        migrations.AddField(
            model_name='demandprediction',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_predictions', to='menu.menuitem'),
        ),
        migrations.AddField(
            model_name='expenseanalytics',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_analytics', to='core.branch'),
        ),
        migrations.AddField(
            model_name='expenseanalytics',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='expenses.expensecategory'),
        ),
        migrations.AddField(
            model_name='inventoryanalytics',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_analytics', to='core.branch'),
        ),
        migrations.AddField(
            model_name='monthlysalessnapshot',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_sales_snapshots', to='core.branch'),
        ),
        migrations.AddField(
            model_name='productsalesanalytics',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_analytics', to='core.branch'),
        ),
        migrations.AddField(
            model_name='productsalesanalytics',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_analytics', to='menu.menuitem'),
        ),
        migrations.AddField(
            model_name='profitanalytics',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_analytics', to='core.branch'),
        ),
        migrations.AddConstraint(
            model_name='customeranalytics',
            constraint=models.UniqueConstraint(fields=('branch', 'date'), name='unique_branch_customer_analytics_date'),
        ),
        migrations.AddIndex(
            model_name='dailysalessnapshot',
            index=models.Index(fields=['branch', 'date'], name='df_daily_sa_branch__884240_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailysalessnapshot',
            constraint=models.UniqueConstraint(fields=('branch', 'date'), name='unique_branch_daily_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='demandprediction',
            constraint=models.UniqueConstraint(fields=('branch', 'menu_item', 'prediction_date'), name='unique_branch_item_prediction_date'),
        ),
        migrations.AddConstraint(
            model_name='expenseanalytics',
            constraint=models.UniqueConstraint(fields=('branch', 'category', 'year', 'month'), name='unique_branch_exp_cat_month'),
        ),
        migrations.AddConstraint(
            model_name='inventoryanalytics',
            constraint=models.UniqueConstraint(fields=('branch', 'date'), name='unique_branch_inventory_analytics_date'),
        ),
        migrations.AddConstraint(
            model_name='monthlysalessnapshot',
            constraint=models.UniqueConstraint(fields=('branch', 'year', 'month'), name='unique_branch_monthly_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='productsalesanalytics',
            constraint=models.UniqueConstraint(fields=('branch', 'menu_item', 'date'), name='unique_branch_item_date_analytics'),
        ),
        migrations.AddConstraint(
            model_name='profitanalytics',
            constraint=models.UniqueConstraint(fields=('branch', 'date'), name='unique_branch_profit_analytics_date'),
        ),
    ]
