# Generated by Django 6.1 on 2026-09-09 05:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('report_category', models.CharField(choices=[('TAXATION', 'Taxation & GST (GSTR-1, GSTR-3B)'), ('FINANCE', 'Finance & P&L'), ('OPERATIONS', 'Operations & Sales'), ('INVENTORY', 'Inventory & Costing'), ('HR', 'HR & Attendance')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('parameters_schema', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Report Definition',
                'verbose_name_plural': 'Report Definitions',
                'db_table': 'df_report_definitions',
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('parameters', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='COMPLETED', max_length=20)),
                ('execution_duration_seconds', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_executions', to='core.branch')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='reports.reportdefinition')),
            ],
            options={
                'verbose_name': 'Report Execution',
                'verbose_name_plural': 'Report Executions',
                'db_table': 'df_report_executions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file_format', models.CharField(choices=[('PDF', 'PDF Document'), ('EXCEL', 'Excel (.xlsx)'), ('CSV', 'CSV Document'), ('JSON', 'JSON Data')], default='PDF', max_length=10)),
                ('file_path', models.CharField(max_length=255)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='reports.reportexecution')),
            ],
            options={
                'verbose_name': 'Report Export',
                'verbose_name_plural': 'Report Exports',
                'db_table': 'df_report_exports',
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily (End of Day)'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='DAILY', max_length=20)),
                ('recipients_email_list', models.TextField(help_text='Comma-separated emails')),
                ('next_run_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to='core.branch')),
                ('report_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.reportdefinition')),
            ],
            options={
                'verbose_name': 'Report Schedule',
                'verbose_name_plural': 'Report Schedules',
                'db_table': 'df_report_schedules',
            },
        ),
    ]
