# Generated by Django 5.1.15 on 2026-09-09 05:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.PositiveIntegerField(verbose_name='Month (1-12)')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved by Manager'), ('PAID', 'Disbursed / Paid')], db_index=True, default='DRAFT', max_length=20)),
                ('total_days', models.PositiveIntegerField(default=30)),
                ('days_worked', models.DecimalField(decimal_places=1, default=Decimal('26.0'), max_digits=5)),
                ('loss_of_pay_days', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Basic Salary (₹)')),
                ('hra_allowance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='HRA (₹)')),
                ('conveyance_allowance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Conveyance (₹)')),
                ('special_allowance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Special Allowance (₹)')),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Overtime Pay (₹)')),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Incentive / Bonus (₹)')),
                ('gross_earnings', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Gross Earnings (₹)')),
                ('lop_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Loss of Pay Deduction (₹)')),
                ('epf_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='EPF (Employee 12%) (₹)')),
                ('esi_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='ESIC (0.75%) (₹)')),
                ('professional_tax', models.DecimalField(decimal_places=2, default=Decimal('200.00'), max_digits=10, verbose_name='Professional Tax (PT) (₹)')),
                ('tds_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Income Tax / TDS (₹)')),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Deductions (₹)')),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Net Disbursable Salary (₹)')),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='Bank NEFT/IMPS Ref')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='employees.employee')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_payrolls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Payslip',
                'verbose_name_plural': 'Monthly Payslips',
                'ordering': ['-year', '-month', 'employee__employee_id'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
