# Generated by Django 6.1 on 2026-09-09 05:30

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('dataset_type', models.CharField(choices=[('SALES_DEMAND', 'Sales Demand Forecasting'), ('CHURN_PREDICTION', 'Customer Churn'), ('WASTE_ESTIMATION', 'Kitchen Waste Estimation')], max_length=30)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('feature_schema', models.JSONField(default=dict)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'ML Dataset',
                'verbose_name_plural': 'ML Datasets',
                'db_table': 'df_ml_datasets',
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('model_type', models.CharField(choices=[('REGRESSION', 'Regression'), ('CLASSIFICATION', 'Classification'), ('TIME_SERIES', 'Time Series Forecaster'), ('CLUSTERING', 'Clustering')], default='TIME_SERIES', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ML Model',
                'verbose_name_plural': 'ML Models',
                'db_table': 'df_ml_models',
            },
        ),
        migrations.CreateModel(
            name='MLModelVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version_tag', models.CharField(max_length=50)),
                ('algorithm', models.CharField(max_length=100)),
                ('hyperparameters', models.JSONField(blank=True, default=dict)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('weights_storage_path', models.CharField(blank=True, max_length=255)),
                ('is_deployed', models.BooleanField(default=False)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ml.mlmodel')),
            ],
            options={
                'verbose_name': 'ML Model Version',
                'verbose_name_plural': 'ML Model Versions',
                'db_table': 'df_ml_model_versions',
            },
        ),
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('input_features', models.JSONField(default=dict)),
                ('prediction_result', models.JSONField(default=dict)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('actual_outcome', models.JSONField(blank=True, null=True)),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ml.mlmodelversion')),
            ],
            options={
                'verbose_name': 'ML Prediction',
                'verbose_name_plural': 'ML Predictions',
                'db_table': 'df_ml_predictions',
            },
        ),
        migrations.CreateModel(
            name='MLTrainingRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='COMPLETED', max_length=20)),
                ('training_logs', models.TextField(blank=True)),
                ('evaluation_score', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_runs', to='ml.mldataset')),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_runs', to='ml.mlmodelversion')),
            ],
            options={
                'verbose_name': 'ML Training Run',
                'verbose_name_plural': 'ML Training Runs',
                'db_table': 'df_ml_training_runs',
            },
        ),
        migrations.CreateModel(
            name='MLFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('FLOAT', 'Float'), ('INT', 'Integer'), ('CATEGORICAL', 'Categorical'), ('BOOLEAN', 'Boolean'), ('DATETIME', 'Datetime')], default='FLOAT', max_length=50)),
                ('is_target', models.BooleanField(default=False)),
                ('importance_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='ml.mldataset')),
            ],
            options={
                'verbose_name': 'ML Feature',
                'verbose_name_plural': 'ML Features',
                'db_table': 'df_ml_features',
                'constraints': [models.UniqueConstraint(fields=('dataset', 'name'), name='unique_dataset_feature_name')],
            },
        ),
        migrations.AddConstraint(
            model_name='mlmodelversion',
            constraint=models.UniqueConstraint(fields=('model', 'version_tag'), name='unique_model_version_tag'),
        ),
        migrations.AddIndex(
            model_name='mlprediction',
            index=models.Index(fields=['model_version', 'created_at'], name='df_ml_predi_model_v_6b986b_idx'),
        ),
    ]
