# Generated by Django 5.1.15 on 2026-09-09 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('LOW_STOCK', 'Low Stock Alert'), ('NEW_ORDER', 'New Order Received'), ('RESERVATION', 'Guest Table Reservation'), ('PAYMENT', 'Payment Settlement'), ('REFUND', 'Refund Request / Approval'), ('LEAVE', 'Staff Leave / Attendance'), ('PAYROLL', 'Monthly Payroll Disbursal'), ('SYSTEM', 'System Alert')], db_index=True, default='SYSTEM', max_length=30)),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='Redirect URL')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('recipient', models.ForeignKey(blank=True, help_text='Leave empty for all branch managers and admins', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Internal Notification',
                'verbose_name_plural': 'Internal Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
